retrieve_data:
  description: >
    Analyze the user's query: {query}
    
    If the user explicitly asks for a summary or to summarize the documents:
    1. Use the DocToSummaryTool to generate comprehensive summaries of all PDF documents
    2. Return the summaries with their respective file names
    
  expected_output: >
    For summarization requests:
    - A list of summaries, each prefixed with its file name
    For other queries:
    - A list of all possible data which could be relevant to the user's input
  agent: data_extractor

summarize_data:
  description: >
    Serve the collected data in the best possible way and only serve data relevant to the users question: {query}
    <important> If there was no data found or the provided data is not relevant to the user's question,
    then return a message "No data found". </important>
     
  expected_output: >
    A list of summarized data using bluepoints
    formatted markdown without '```'
    or "No data found" in case if there is no data
  agent: data_summarizer

